// Code generated by ogen, DO NOT EDIT.
package api

type ListPubkeyGetRes interface {
	listPubkeyGetRes()
}

type MirrorPutRes interface {
	mirrorPutRes()
}

type SHA256DeleteRes interface {
	sHA256DeleteRes()
}

type SHA256GetRes interface {
	sHA256GetRes()
}

type SHA256HeadRes interface {
	sHA256HeadRes()
}

type UploadHeadRes interface {
	uploadHeadRes()
}

type UploadPutRes interface {
	uploadPutRes()
}
