// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"
			origElem := elem
			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'l': // Prefix: "list/"
				origElem := elem
				if l := len("list/"); len(elem) >= l && elem[0:l] == "list/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "pubkey"
				// Leaf parameter
				args[0] = elem
				elem = ""

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleListPubkeyGetRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

				elem = origElem
			case 'm': // Prefix: "mirror"
				origElem := elem
				if l := len("mirror"); len(elem) >= l && elem[0:l] == "mirror" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "PUT":
						s.handleMirrorPutRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "PUT")
					}

					return
				}

				elem = origElem
			case 'u': // Prefix: "upload"
				origElem := elem
				if l := len("upload"); len(elem) >= l && elem[0:l] == "upload" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "HEAD":
						s.handleUploadHeadRequest([0]string{}, elemIsEscaped, w, r)
					case "PUT":
						s.handleUploadPutRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "HEAD,PUT")
					}

					return
				}

				elem = origElem
			}
			// Param: "sha256"
			// Leaf parameter
			args[0] = elem
			elem = ""

			if len(elem) == 0 {
				// Leaf node.
				switch r.Method {
				case "DELETE":
					s.handleSHA256DeleteRequest([1]string{
						args[0],
					}, elemIsEscaped, w, r)
				case "GET":
					s.handleSHA256GetRequest([1]string{
						args[0],
					}, elemIsEscaped, w, r)
				case "HEAD":
					s.handleSHA256HeadRequest([1]string{
						args[0],
					}, elemIsEscaped, w, r)
				default:
					s.notAllowed(w, r, "DELETE,GET,HEAD")
				}

				return
			}

			elem = origElem
		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name        string
	summary     string
	operationID string
	pathPattern string
	count       int
	args        [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"
			origElem := elem
			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'l': // Prefix: "list/"
				origElem := elem
				if l := len("list/"); len(elem) >= l && elem[0:l] == "list/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "pubkey"
				// Leaf parameter
				args[0] = elem
				elem = ""

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = "ListPubkeyGet"
						r.summary = "List blobs uploaded by a user"
						r.operationID = ""
						r.pathPattern = "/list/{pubkey}"
						r.args = args
						r.count = 1
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 'm': // Prefix: "mirror"
				origElem := elem
				if l := len("mirror"); len(elem) >= l && elem[0:l] == "mirror" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "PUT":
						r.name = "MirrorPut"
						r.summary = "Mirror a blob from a remote URL"
						r.operationID = ""
						r.pathPattern = "/mirror"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 'u': // Prefix: "upload"
				origElem := elem
				if l := len("upload"); len(elem) >= l && elem[0:l] == "upload" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "HEAD":
						r.name = "UploadHead"
						r.summary = "Check upload requirements"
						r.operationID = ""
						r.pathPattern = "/upload"
						r.args = args
						r.count = 0
						return r, true
					case "PUT":
						r.name = "UploadPut"
						r.summary = "Upload a blob"
						r.operationID = ""
						r.pathPattern = "/upload"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

				elem = origElem
			}
			// Param: "sha256"
			// Leaf parameter
			args[0] = elem
			elem = ""

			if len(elem) == 0 {
				// Leaf node.
				switch method {
				case "DELETE":
					r.name = "SHA256Delete"
					r.summary = "Delete a blob by its SHA256 hash"
					r.operationID = ""
					r.pathPattern = "/{sha256}"
					r.args = args
					r.count = 1
					return r, true
				case "GET":
					r.name = "SHA256Get"
					r.summary = "Retrieve a blob by its SHA256 hash"
					r.operationID = ""
					r.pathPattern = "/{sha256}"
					r.args = args
					r.count = 1
					return r, true
				case "HEAD":
					r.name = "SHA256Head"
					r.summary = "Check if a blob exists by its SHA256 hash"
					r.operationID = ""
					r.pathPattern = "/{sha256}"
					r.args = args
					r.count = 1
					return r, true
				default:
					return
				}
			}

			elem = origElem
		}
	}
	return r, false
}
